language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    secure: >
      "EW0tABvIKOkIc36eFLVKuLblZREBQaQGuRYwbivvfTPf1JKhZJa0OoB71sFOWAUllOChS5CuOXm8vJKolTGERYuD86d56y4E6wrvsMrws/8gCB8gWJKFJWrRiDudI5Spur2XVNCLpYCCDjgMdotd9ysBH67RIrYzWeQ1gJITLPFcFYVzXrWBpMsyroyKLWwn56kLzJUairU8xwvqzZJ2nCpywawI0zFPB336rxaOG52XcXwpctAnqGBXy3XaQfldUy8m84cr2nY2JDOMxTgXoMaK5EIEfBcKxUlJOpUuibpaqM7OeOeMXNwgscuTu/zNhJ/RsNJty3mq8wzB9raN412dnGGo7ISpIlz8N4arAqFXh/UfJJgMR9/QwBmrvLZTkj8W/ix+OmXmL8k9gsjvZ2kXpdWvA2a8n/PFSQJUJx19IPZb/3IcFjLOdHvI5zYKNtSuhfHCWKeBldW+/cSpLUBeRRGMwTfjsRIC+EMtXs48A/pMm5F5uzM0tbva90Upw8iyue1uYX7SoW4f4DIGlttp/J4hyWHF3dzxlRltfNlpM1ykmCuiYkre9Rzvebsr9WX8FzCzTtFH2rdLSjwcXRONKB4mXAMAzLhWi3xpKfagyx9ayGSMWwDYCyQXwfQxd4NM9TbPbOXXr3x/+xpb/7PXmCKCSGvaPxQm02oOsVo="
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: contentascode
  CONFIG_REPO: docsmith
