language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "ZNtt1wMXk18Rc61d6VdmbFV5GfNFx4HGndOcqiVJcomVwl7befDOGQYIlRVz0yW7bi7LXyszFWSz9E/CLAVSuFlN0LCrs7alq+DLpdghHvAKOf62flzFngMKpOOSXf39zEAnGwQ23tcrbDJlFo/dKgk9WixFDiUpyVw8oQxuJAq90yWBimn5Sz0vltBhzMSO+0JeMjn02HelFHWg4krvffv6e2xC/c/nte90daA1UcWRfYYbc972eiY1VOmzSmizM2EuPCJDuhyBzCLSTleNmRlufX7nD9hmrx2UHRcM/Bx76ZjJ93DgQ8BHa82Y9nKWVJ9t2bjDfPTGHCFj1pdQ8ptobHrVDm9Nqryr4SXFydLV6oXsJrnqf4tjCrl1hx03j61IVkCJijuif1jP9HSK+vOFgPX0OwqkYjfIUsOPBmXrn8T2FtU4sYI/Mkg0hpuACVX6TCFJKspknZanUMRA8cPQ0qpLjneeArF7mI4SDn1WaR5jJwXNYllkXNopn6Lxi3jQKXoiy5PagSQWDIA0JxnFbEDcrf3YvwarQBz+C13vY+51e7X9lfTo7nOuI14iVgb8Xle2Wrd6Q9RZ1vH4PeNbaml9GY1zArjYl41bDWws8sS2N4uLtvk3jNU0XP27vYPMd43Jvi7cDpeF9k7AxJTfrSS4lwjV0XVCGvH22WQ="
