language: node_js
sudo: false
node_js:
  - '4.2'
branches:
  except:
    - gh-pages
cache:
  bundler: true
  directories:
    - node_modules
install:
  - npm i pm2 http-server broken-link-checker -g
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "sdctAtvjP/qwSctVpVUgOcv4nkFvx0MXBFlLwJyQc34Bx/yyDe+45PA96H+LNvvEkWivxlTBI2tcnRypJsXXvq7+VyBmTUZAemOdHobQmu3X1WYrH7rWEjwBZ5eSehXF6RON48/DwBOdJxWDf19BDuX35RcSJadHPdcLO85at72vs13NPUa2nx9IkGg+EcfO9421G8Wi4uJBQxFnKXqZftbjpAOHiHcxQUz3DHwrNYnAK1iSbvtnodeqkw/1gwUEUGHOB4qsNTqQEGf6X+gs+g3a2biuzBhWp/UCvKvz55HFoPThiXmcRtvtXBQ5qTAJgOkZF85wkLDc1VNsbJ0CugEakU2RENGd0XXDIN8k7W5eXqhpPedrmAv3WRkhnNiawmnC9rHM7CkzfICqcYhJAcTUlMMPQTtutfa7jOzhz/P3Y+7Vkof6catRVDNTgsphm715eF+B5zBI3EDXt6QvNEPwSz7JVxYiIZlysvlPujOyx/EHgL2d1C0e0UT0VbuuoYc0kTfbsJEGZPDX3NzNiF48e4HoeCn+reWHwQyj5hiw3CZ9w0qBN4QNjrYqIboAH7BwEgqYbSy43XnKf5Cjnlsvf/YAs6ttm0IrYxJ5n2eM451FkpOLyYf8RKglINEobpxgg2vX3OcJZMSMr/g18bzY73iKc21jEoBufYTw3w8="
