language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "KAaH8Lb9v/4RgU6qtXKNTgvfHtqh2cC7+8ZeVycY+n3EIb/PFBClVM58q3KCM87oPKStlnq2NMPqksnr4FPErhFAKKRQmwqzw+cWBmqS15aCIe2nu+02Wo4EiJIjBBRzSh+ij/VCNC2KZop8Fu87zfRhbv7kyqF19zzhERlxxDAFqcPeefdRy1AhqwC+Tvvlb06J5IMiiIjTp7p8HkbFLUM5MExj8pXJfTH2Uhma3HMTxYWyq544BFJgRSqhlWgr3syg7sj9EpjQSotpuTqgiE3BVKMJoaitA97L3v2LHRxanun8G1Sb1KsixSEn6LWYHAs3HzA1f55G4jrOyBtpTRzns1RC9+bam45b2CoHO1h7eKuAd8/LDv+eq76rhDXSUDUFvmtVvb4TINdxLmEnDabFnKtw/1shgvlgHVQv7ztXpw4I7mTct/Yz+8XTeMvfH7fkAeCj9yeW33mcZnHLbwXy/olz+3WyOP2bWhSB1D9Gl9xaznVJ23PxZKNrCHNrmOzq9bxEQaXR7nH+3f59DfcFK/XiP0tSmTkcjqdlXMOgXVuWt6sb9Uz52wmKStwpMFOPm11I2C018KgT0ZkYhC4UxZXeooQll9OcUIPk/hUnB7fern3QYVfVpoq8/jF0y8eQneVPy5LwXvDIgiGFKF7hPJ6wiqFIF/OGFBLIT1g="
