language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "CFq1n8CpiA1c67vLYVXSsLdp47LWWqMYX1h0nSAKgCmiO+csWoLSamq/QegxLbDn+gKY+Dyh9Yy3yHjbuzMNN+VYBJDkLTuuBKYEG/gPDwXKysZoO4dKgE6z6PCVCjX9/mjXI2PbpVUOynKE7tTN++qYlyyIuupQNDNqI26s9YF4wZAEKQECBEhdqSnXiUdbhlYUQQOnai2oHuoVgrdYO/7GHy6Zkgw1G/qXrcrqd3ujRFB3ivUhwNTbMcbAOk4F5VSbvsgWZPObVtM1G9F7PaZXY6olRXfEef2ZiL+rn56cwirk53RTEHluWL2w//fgazMJwS6jXN7Uz/MZ14nVv+/i3kTBgEti/yHqlx4yJjZxdbIlNxGnFvpznO4bGuJGJvdHk2Tj/VYGF2gtjZWDQUzXkjxfz5ccbspO79lB0mgpZVcPiQDZI9KOW2U3wEQaWQlmkozMGMgE0wOcMnq/GKrYf8xHXCZu6jnEzesaI+u9KXMkV3qbZqniz9QLQ9K7igB0mVL7ewuK7/I9RtpTIY0kXyunySfNQ5srv7wNJtOTQgYNPFdQBNImqAMi+MLGHTAVftTGlOAwKj6PSp2uodVmuxMYWiTL0GVhEP87pUlKxwgrcfNL53MUFAMgYZjhoy27m5QPEZaUVcau6zGX7x/RBtmiKch1Ppixb/EeP6I="
