language: ruby
install:
  - bundle install
script: 'bundle exec rake site:deploy --quiet'
env:
  global:
    secure: >
      "YVsI37Pi4FyRg4MXlshWw/EdePgzrYTD+M5JhgKAaWShyPk4pF6jF2WPfV7PwEGo22q5EAlU3MX/EZaTCQYaXG5LuEjv1oW2WZ5HX6OAP0RAWEs3ZTSIHGP8dUeQQZABmnjIxd9oFvpNbsrphVpz0ybBSjMc+xR3PiElSWoNVUMj78Ym0low1X6uZfUqTDTkIB5PW1OltN/SAigLFINj8mdZ3n7LwQ0Nn6xJ2GynpBdSAm87WpJNlDLcfYuyaJDPJF7542rczlglMHq3raou8GOpPi9XK0DYZ3F02TECBN+H3Jau+/Etp9t5qfhkM7Lygle82vmeGrfhuMGA2nokAVCRHVUl2KF13WHIHZRMk+y9T3JU+EXJbf6/L6/GdenjUwkUAk9WlUW3kLI4HJaiupS+HSCN+growk/dZm08MZH1up0M83CHJ8kQIgEbQVyoydKbmmXg2yyz/HwNg2PgrlheCHoA4AvWG+3gBwRFvE4kY6yRNxhN4qQOkjwOgNbi7RHDoHRaKxNC77eYLU1ZqrgBXJRogxphBKLWnpQajjBWIa/RPBUCSpImQIaXlR9NKLltZk5ZoUsjkE6aX3ilXy6ELDfDiPmRPpACuQ73RmmTrJaUMKUcXo7Mejrx6dI6hhiaTydF7Kz68mfP5m4q7Zai8sgjAr7O0SFV91YKGdg="
