language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "lrdW1nxSXSWys4fPk3pQRe3/DNV3U9Ig1pq6idj3uDNPKyfgrm9gi1eDNlHQpGQphws5yL2VLNNf/ysaAjI8wsDTxC2D2bONvVYWF/0R4AJdD0BW78GciXg74gc8aZ5YcQFanXo6ucA5DJ9hxmrb7LO1Eo+dDy5bkt3PBGBIJea9SbvUIXK2JkjjgAGVzD1e4lNQKR6LPPbIt5ct7Vh3Q4w2gEDYlOPGI4Jo/YZDJFCphcFeJaXMRSlUI8mRzcwIOA/dEg2zC2Mkrxr3gCkzkj6uj7/54UdEdqmEcDAoVFi3828/NH2/cNEtUHLRMk7YFf1RVmJTg+AMCUcQD/3Q0iJt99yWJF2bi5mZpct09kyh2o9bMCNtDVrzi5chklnRtEJqDGGAaiLaN6hm9sNsgn0MXN6wr5EAD/Xo981yGRKo0P3ZEjTGbLzWx6rpbkXNY8Flhp8sIfxJYl6HkDSgKV8oBUNg9KylOTP0FvmVTvyYrT1zwAAG9LnxpJvEwQEjKh20xMs4pZIe0vBfVA2vKSvdLiEMWbfegMTi3Kc88tUBGY5QJcLKb+bbQq1G+M5Oa+peXk7grkrAt5KMiyX5aQdmeZXSMMtj16YvrbvnEXGaV5h8iI9JFp7uBDYqB1CfFszAsUtd6qd/7XDQfU+4eCbl/jBrleax5447d8FLMII="
