language: node_js
cache: bundler
sudo: true
install:
  - bundle install
env:
  global:
    secure: >
      "i04HGwqPiQ53TD/PSk09Xx5kADjD9DGWwji3YvHv53tB1V8YqYVole+vTYvKb0cMeP5RouW1fJnEZKiq8PliNaCRT9JYR1bkFjrNR7SfFMv2wApwQCoS6oN3T5lWvK3IQg13QYs6kd2TYsHDB6yGeWVz2grJue7JSBJ00Bhw511b1Plu5epWjC0b2UvfxB/aSVIleuGvbTe0BtAzl/v820hz/UyyWbSM5edy0l1S1jyDYeMJGcnZitO0ZwU/6MHmfXMpvs6M6vTHjw4RNP3bPA7LILiw2jluJALOqE9lHX1LGOs0mV2h7NpLrR2L2XkBTY5Yq/d8vtm2VCPXkh14pQpIk2QVuSk0kYO1wE1FunurI42d8uVa5nxrg/eZG90HxtqkH+CuM7rcWOeMOJovlQUzzTiKKlzpYBMrj/EVXkavuRIV9rF/L20R/4MSZnNZdlpEf0F5ZXeNpubF4QMDo1uhw9Itne2ZUAVdslhOOgWXfCPJGS5nN/rAvc70rCHvisxan5mrwdVrCFSigpy4DNm7VuLDm+YZwp4v0GEeDz89nYxv2BcUwgdQ9b/D5/QmwaxgCqUFhHdwz4MUL68HaZ8E0HX3dHEO8qUgEqB62s1HUhqOB3GNjPuzNTXGZ6phCr67LOGobaAwwj+zQyFlU5XhNVzYAHStf3cOXgha85A="
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: contentascode
  CONFIG_REPO: docsmith
