language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith
    - >
      secure:
      "bjino4QVL1n3R+tBehuZPCCLLe8j4qeEjH589G9w7YZ21DCz0z5xxl92+vUYT+vVCOXTGwtzu02vT94bY0Qkbut/ouj+IJSdTo472M6a0WRBTCuHu60Fak79gfF4e2NCn0kX/KxdSPyd1FRUtiy01ufT5umpxVNvkL9IZMC5uIOmQfNJHBIMrvSDRI5UWVrCUq2OBftYbNimXruXgXD21ygVhphPTAglHaBK+LKwXG8JFmJaMs9CoJXqsOmb7NhjfAFvvw2Olh6Ws3/01DOeZsk7s3JgpCS1XKeTG8LMy2B7GggzYaT1pH12PAscYwrckcfHdaUctI8hd5HhAaLOXZvqZ0DkcB8mSn+EaZ/0dXT1VSwmsgyW1fmD5U4izh3NN738CM2ukDvQpHGUyxoAZca7y+EPlu5u42Ispi6Rei7ZZaBayYbGD/XSDm6vLYPVJ7/rfKwFzSUpxqSPmct8T1NHCYz6ZSFvqTmgAleuJsGhmJ2eKMAPwyaBoCG8RUs4XnOyqfeTiD6kyD87GlqJoKzuXTfEWEBD6zh/6SiylLW8abo8EXGzxHhmFnw5aj0anBmxBoBuIMcQ/FikPpP4QpQUyASbymnFeo2nC8n/pPUuy7b62avgtnRebJdqo8bMk87HxTom36KL2rKK0S255QDvyAIT+Ly0rnSCu9PMk+A="
