language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "sx9jNXFEpzawIKSC3v+krSELiCdpZP+MCKJgqSre77y/5CC0mFpbJ9r8MSPAyp6Oy8lomePKpM2l4Ior8XBrpZOsAJARGiErVuJB45YnqQMWwZ4ynPq7b2zepsjlui/YvFly5qdgkmzl2Oo93PXcw88x80VyKRkVVKu/HWaHoOFjq9AShU13rqBuDXHYSqK4FGhrt25CoszQssXZgz7TX1b6+u4aCjR0H4nWFf6h6N3YcIU2bP3eF60LyPEujRWt15ZmAX9w5lvKGsxL/U5mbOBQ9Su+HdD5bBIX3nEiKVsRF0MVfOvcoenqWGYIjDhu3ciSIa85je+i1UHb9FiHyh39OWh0GUpr3jNhbNz/+Pbm1Aae1WgVU/ojlAsWixFpHW4Qxv/fzVxQsw3S9uMh8exaWjgP3If/nUnG0d/7WoMMkqaRYGd8i56U5wfwc4Ywh0yV86chZpb07CfKp7GqLz9M7GUGSMad2pJJ55mKBMwgcmg21WlPRJeqzwwq4BXvju3BCl8zOCflEQGTISk34ffYqZs+QoRhaDAlf2+TMsbwuqHy0hi7drn/WaMCqlLt4b0wOFKw0CeoHxgOZjFoh7m8p/z3IDmwRIfZFcU3fmFgMBjzKpfYTjfK4vml/6/7AcueBamsWXU+REdN4GZjtckMl/t12jY8PVHNT18Hmp8="
