language: node_js
cache: bundler
sudo: false
node_js:
  - '4.2'
branches:
  except:
    - gh-pages
install:
  - npm i pm2 http-server broken-link-checker -g
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "TfFRvAouOY1PSkQadKzRSXExqRpgQOrXbrjuBfpBqtW9KT3phEMzaj/p7uLkMNgoMWceNCPqxvJoVPkHEv6kGMABGZ1EYwuIYsKsoBNqUjpT7E0EGVb1/57dd5G1Ycq/pxeXjaBQ0+i+YJh/xknznJR7zVrZc6HpNZTluGUaUpNJZB/MDPTzVymtdpkwI8vR1448FzRx+/7ObsFOKBmk+Do4zi1XQZojwdLbyaELFD/33fvauaeovENmJChC4eKtIkXWvKiPOihpMEJ67kL+XvaZDu1ppxZv0QuwIs1hQMEqJ6BJf/ez7bNP7VkPCWORcA8aFA7WQpgif5XPjv3XtedX2aFjkvoP3aQWEvk+NWp6+jhI/iI0WM6yg6mq2Rk+9GJQtFm03ge9AjuCYWvskHxE318kFa5i/kCzyU8ly9mncREeDyInyZmiQveL83ZbljqKhsENkPa/HArL3I5JvpwcG5lA1hHS7pBU55Cpv8VeSDpCYHYRe1yejNVVIqLnX2qMguueP2ROFO1B+fB5OQlD6z2adxtMtXXB8pxM2M88KtbovLl+jwHWCnfjMyu8M8200nrdQ6RhuGrmfvoq2l5WlhCFH4P1ILJWpKuQ67h468Y8ymNTAxpPlFmCeyzzRralJA5C+1INNvOJKJBLilpdPU65SCZbjiAyHZ4Gi5M="
