language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith
    - secure: >
        "aw22HY+sfLOsvWllpQY2E00r8OTNsHWL3Wa7sRNm24GqVUXaCmFBvw28ya9cc5tHD35V7EalydiKLR0A2TCmqW4WqY5cNtampism0XyZLqyH7NsYjN3oankhaKwxXCJV7S+n+SeX49rDnECjH9ilEYEmfMoKDJgDb4cUCTUA4k+ZVMSLwJS9+2ShFj+yUp37H9CM3rQ/zlbGzrftjuml8YRCXGnD4/Miv87ciOZxSZZgefPQPX3DtrzW6midTLejQnE38NbIb2gF2xGAowJZ1ukG6HEQyH2+nowMpFUID3s6TE6+wY1viJ+w8eyukg/AF31wPaGnQckafD2NE2GKAka/1LCuSQr0kpok5tCMBdHulejGPUbpn4ZQ29FsRDIMe987J5s7aJ+DFG/iXaNVmJ7tC+eM1tD1d/CT4AzurprESIIl+OMPbfsbcIyg81NXZhrPMDXJ2oTkgi1aDclnvOTeuffwCtv31gPZRJEpx8Taw001ergCKLjPOk/dNVv7CrUHRtI3gKaxoSkkDGRj54vy4g6enETTHRxy4VK2DZQRfgArxaozSsWVLidDChzu7q1maE/Y1ySVwO22EkmdLHOe75c6dubgLr/jN5U0JBjAlXEzOmSeIJncSo4qi/ISq9My1kECSDURZ0t3VnRwxEuT5D507JpZyj1ya31DopI="
