language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "K0SCSqcvvX9fxMTKZgQN+AevDqwW7U7L0j4e5iTBWLpVERQEUiX/7vcZlb71P5UT4tTyxAYPHQVgYAinj5jrIGxy7wKjuSVLRkQVDGSaHOBIFpTgoX0jcY1pPGv5yDLmrUsGNZxkOyR0TMJNv9Wx6XL4ye2kwHvVNY5NU37GewaTipLKxbxhzHaehC8uGeWfNqrqke16it2WzDqkVoTjdGv8pniD5nCw+m9AtrjIW4uAcDp/v3gkJkSo75ZiGWo7ZCAcJM6rzUPwH/rs1rS3Xr24Q/ZR8InFnEbO6GjhDEcGbyK0DutsQ8JSyumNT3Zi8cl9sE+onHB5HBY9eqpfbe2/N2F1QeQrnuyfutob2WCS6/vmTnE+7NKAsmHaZ8PWGH3vWKnL/vDYT1E7yAfYKH7DZCu54QAkd6CWgJqQKBPvIv4DF7AxCCl5ab/aBMdR0VSjNg4tc9zK6P4iu0WJb4/L6KX1io1vXcfCLYZqPo///2UjtvI8NZsFchbNknHIwYPDcQf/UohiyPRzXInXt0YGebyNmbVdVUdgKKGS3qf+5sZKkZOQFeBTFzrThFJLQDhpRI2FE64/zAklJOheUIrEIXrEF4ayTgu36yLPotAGYJvdRGUD1V2hTxr7O/3f/LQl8ztqHHlVYjvw5bKs8Fkf06o+34DDDMgPk5P43Pw="
