language: node_js
cache: bundler
sudo: true
install:
  - bundle install
env:
  global:
    secure: >
      "YNGk0yvqm3JiU+UuKCo6mzLxcD1YkHIYlbq6KrrwTLiRBU2qL3Shk51NP6ERsuDun+tgWRqMjZDyrFV/1njRHqQNHDQytPd0apVqazTG5P1n++xC4StjazAMzOa1hhjxp+T0odru1dnT71vM9L3wzgTrC9NTCAuYgG0247/bcxFNPNctmqPFvWNClB2GzkLBUdV4ovrC9fruMQN5BuRMSOGyKpd/GGbyD9zz4rRIezSIKm7Ll9xdPqoueEze36AisM1mtCKmEldOnCxFf4fQsztBNGll3klcAqVmnFanBpaOF+pBKZ81zswS9vWZF7lkQR59TQuicBAgCNVeOn1T2oss4PjhqJhGnPT6bQxHIB9pp0sixEp0Z1HVSTLqU4RQRnt7z1AHv9SN5mUlWa8kIQSZNV3Jbsd2cvfmk8Sg1xJ5yJazs0HGetutCNDrwO6hz33R+baspeq4384cDubIWtRxrwOBRiFBXsQEq0kUHmdM1Cs+BKodT/ScX6E+KVf+h9qKka8nkD+F3Nt8D+0EtF8Ka5M6V1gRRFKpbtUDqKrqwDZw56cgvP+1i0KFrF+c5TjgGQba256oJifcWtZWUn47hHqmb/IibIDisKn0LiTcf9cxhSdbQeb35wG8nOeZvfzL+BJoTgTxo0l4yoLVHi3bmMExGkgWPTmJwAHNaYA="
  USERNAME: jmatsushita
  OWNER: contentascode
  REPO: docsmith
