language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "QXhuZF1vFNGW8pwBfCAW71SS9ZwqSpijmeHU1rNR+pxqcJeW+7uJ9/FLDR1NwLBLog9o+GgD71mOrkv71VoAsa4rNxaZU7dFKwz4+pimJ7L388AXrLuGA+pitbLKeOXKwhpkrxFLNfqPjf0NFKmBa97c+8Al7Q3TSPP6bB1jsaqFw/zbV1DyOtygsGGl3MJOqvgJ9n5+x87WQ65IhyfBlMy7UR+vPVJZlGCk5eRlXbWITpL7uFDsaVKgpOqKewnspO2hi6WnK7M9tFPk9xYk0+1kCeD4gfrsDDSFamaQPim+PhU7eYVHyf8akvn4oz63VtMP4oms6B6hspox56aaLCfAaVaYsq9afL9XW/931nPozDmn1MCZS0LM+zSq1exbyfBKFFTiYcKN/AOxUv97sq0g/9045uP/jS90xBlJDQNA6jZ3I1kmRfFpumOf0pnBP5QHgLdVxAyKFFb7teyxldLYlXaCJeiGjOgEGMRZcVZKOinz+si48g8VeMForva35A+DSmZPhpeanLCB7l47dFrRfK/w8tQPXJW+Yj6Nsa9IlvhRYPHeXQMeanCyzyP4b6Z5eo0SY5g1LxunSay2fgxYjRdfrtFbaXl4TMoXdeit1tw1uixzgg16FvTrg1Za8w3H6JskaN4iEdzYxyqI/52uCpm9nA84AThjjOcd5pA="
