language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "FQCLL1o0M0DtJbPHwfkl/dx9PHPPUGXCBMnMUJeFnR8SJyb8YX5zshUQyo55T2yR4sPAL3AXwJVQ7eoeA3GF6hmCuUPPrzNGUjY2CdOtDgHuHRlkzdZsbtn9Zn2S9C5RhJQoyhAvPgDM/FDU4aAqBI4nZRvvXU6kGRy9gb4PFTW6Irhz695sLu9Znwg9qcmWMnnT6s9vak8X50CIBDNVARzK3+HJ79SP9P6Ry5zxvWs35R5cab8AtGVZUAeIScKu8zKkBcGMVuaI/JKAoajrWqBs/2wGSvKEfeNsdvNOyVGlVpYUx4mJfntGI7KHYDkaqxAHqVW4hN0hwVxeiHRPZup5Tp8VDSSN79xcv2MuxQddMEcpUHGQ4KKJQWYOjHGgM1YBEYM6gBYeVgKQSA5X+RyFrOpJP5Xit5J6shAxFs/4w2OhVH94DJf3kdfUCzo4ynl7tEmYaORpUT2Uv2AP9lOM4lnEOk48TEWL75hbpq3rCqPYU9Ntp2/dzGutjNXIbANdm1gk246/blopPZXFOEkLoG+Kke17dqCe1VUikN32vbSX2XYu094xPGnU4+iiQh5h3lrn1OqLCBfcljRbD1ufVa6XOtSL7XK/TZgN5tJJwWlufSJiQ3uiU37xXl03GiI3g86HidGWhlyQo9yPTpmU4ZrKOyrCHXc49AfURss="
