language: node_js
cache: bundler
sudo: false
install:
  - rvm install .
  - bundle install
env:
  global:
    secure: >
      "bAVkNyBn12xr06Fzbn+zRTCG81kgHaRXWPvs4s5QZ7kfaFsKXwnBpyaAXn/nZxkU5b1IBq+SrAmXoPLnQsSEx+t4wvHnZNWjJIwZuLI41wdFceq5TihlJeT6esTWSWkIpy5Sea29RqIR6j5O/PkCDvefK7cOt7Pe2CNZOHrMn+S41ArVZ9mB4Z37jl3GdOHg8sQ8ok2OSr3uSZyiizWLENd014skH8LpB+cqRdyoYO7J3BVq9gMMWNcqAe6Dfd9GhUDKRD4oSW3YWgyvdLX9e0cASY3leTJNSXvczGrBwZ/m/3CFHLxIysERXlTkgW51CG5u4tiVDaRAkuSWORSkCSSZSbSDW2rSzPYOWWwPhhAqb/a0icCxoNNwIvnagbwkHdpzRWJy/oxn0I8fYw9zkBPBiboTfRvsysmltYcSxqf/wnTl4z1PRTtQ7r7x3cvknX1CAIOwgQgXTBXluds+Mr6qS3s+gqcxbmzS/zrj1CXUf5xp3Kkx6xb+Udxu1Ct84I3WddnuMBzOjfb6S0k/lBIg2RDjs9dkSDWzO/P3xioQ7UIAZDxvuDV3g/Nw0rlvSMik76TUoM7SEVos+Abd1gALbQam5fVPldZ7pb2jYx0iAfbQ/pNwYbncuzOEHGVLeFDk1GDLzbJJ0hI+MdEVer1QC6/gcEN+PrUa8+WSMWg="
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: contentascode
  CONFIG_REPO: docsmith
