language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "MdhQEcxo0G6R0FaBJ/eB6c875WQXteynJHrUy3sNyrvn45KedOi9XB5pA9lwaJnJPpiBmuXX3SpWcQKGqWkbVxocxH8Me/xCKzrd7QMFT8uJ59MtADUtWyvc/EDH876AApVyADtZAKhpirhVEUiysXfv70yOud8jJYTEgJvQ/c7IO2jDBBY5IF3LhOukdDNykJvEnGzyJmMmCze8E/6IAAkohag2n72JoZcGI7LJM05lQA2th42w8xu+oqgPgcFJRNDKXmfgXPcXHmBp6KFEYU46stlnn+CBWIbSb92oCZWuZMNZ44Lzrb/mq34V2FtaFCR+RB7Cvfb0tLtlmp+OsXLIJAFIzMnoEIY4YjT2zBxMq3TN31+6YYL+5KMhosXtE2Kg4siDKaoDF2JzwfHbSVe9TDqY5cGM8DF8EmhPK0lT4eEqKPgU1rEujgAOQ+Qze9nENBg+vCYUOSF1lO9Z2waZGzSHP5khKopmIX67CR81qNVBFnI8EXvWY77YFwEMNNulB1okVjJxMvkT6XZPt2jKiFxe83jNc06zUzEn6ZZ2jttDfZ9rWm9cqvhI2HLzQM9R8PN/0vg0pwCiI8AUmTGY7bpAt687x7k4a9L272NKIfQqJz9g9QE4RjV5vQQSPnBkCc9FhNw2Y0h5SQUgNrDYmLDsd+RW3CpnyWF3Oqk="
