language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "Zf1z/04n0ISsZih8EI44vtI63LHdKFvUBKUUxWtShmKtOk5JXBgHIYESynMDZDbgdcwI5Lgss+4H23zbsQbH95P2txJVwAlHRRTwqfkQjvBLUjW+db3bhtw2x05uTNE2jE5vjrvXM2x6/4Pr5qUVj87fYXt1EUf3D2QHBr9JEulK1TPW+3OgOe00P/EEg8rBELYWckqVI/J4nAyceoX+l8wPS5Ay5rlmgwa5GA1ZIWhR5wlA1n5mgSs8N/+nJGwHYg/OmR65yGeg00HGOxbXkLzDGmTQy66/FEPJqFdIAStnYWXDyO2P22jCYXVPEWWkchQFy9KN4jzg+9W42MF7LOQEjElzLWaokH0095LAhQmi29gGMYgHCBD3/DaR3VCEkYKjwG5ZVjrdk9TEVmrnazS9eRnsMFJ5XyaWmcV7mn7/9w1SeqjSKQ/gjU6741ompYhcR6usKYfzSwSITjrmhVrWtibINUgRImH3A4PJPVkk4d8Kllq0KnNh4KxQCxV0+z7QuqcUtUXVV/KGtIYwyzX+A7PqMnMYnC7w6BBvKzgRPTXaeNZBcoe2sZmK2kW8Q7QKRD00IP6qZmAOFWSIkuf8Qw7nNzqHwUOXi5cAqvEtvvNw73+0xfkhP5mvNADvsjubA3FffyARjZlC4rW9oD7ia1RO0KSJGRbdj5ZGNc8="
