language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "Emf+ItAE2QcHE3fp/AWXN0yIfny8JhrZ2nPwwmzXa+tuHdjux746/4H+2Wt/AEEKui0IsCqaEPZun2mYwk3A0T3ox+anNMmdWMa+qEzE/Em9fBe7vjhCwR6V0XxB03JOyTvq1cQqAnJrD4zG2xn7ruv8mXYb8KKwWblIa9kkFmLQ4RCnyr6EWnSuclaTIhCNuFkufA2yXY/DNLFlEjXQDkipTNxg85hDNtDTjNvrENdSw7N7PeU/bp00UKioPloW73njEu1a1ZVkF/82bIZccf33+COO41GJfVjmzUZKRxFWvFlbM3suEmrN2mgTtpn0bX2O6ToYhMtGNyVr3ZqZX1pSJPJ4GaLow0wRU2i/jWd5enwyVTRnxSWv59F90n49ZVSHr1BKI70vSBuXvXBQ2Fp3e8NPUUrc8u9PSdEGZo20Lot4162lOzlbgVv4mhU04HfhYSDrx+uuxICf6VKhlpJn5ekeUxyVZMvOZ20l/I5aKVnqAeG2bTDOqSEv+/H8V9OV8wQ4eRrM/WJfZx+Dct2X5JZIMCF7s2ZhMs05GAfsV/k2xgbZvuOcm5rHpY9t7d64vD0VtEzkleBD9frHWDxjzQ/CYGXeikmRmh4tndyBuWHS7YZ95h7Vl2xk3UaBfcDrdVDXYZh8nhyECFBgYAFGWX4ceF0+LH2gE4vu/qw="
