language: node_js
cache: bundler
sudo: false
node_js:
  - '4.2'
branches:
  except:
    - gh-pages
install:
  - npm i pm2 http-server broken-link-checker -g
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "woeAhkF4qaAMQBT0U7KtjmtoMcc4G3RanGZNUHDsVMnHe0bulh5kOu4xOgRsKaEc4hxm2QgfXCcqfTcUTVYsXU/jjF22T6JA/GWWuLq8FSjxIV4l46SZFtNpcQxpJlX6veEwrt72BTqfzBcmr/ZQgIC8hvN0dWhqFA1Bc1wb7WcSwU/joCkSSZhjNL4tipN6BQEDPXYO4zYUvmalm774fOw8wkEB9FXb72FeipHti9zgoGfUHKV40MBhyYB7ymAhi8H/BgT9FqMJJUpAM7ewvXXPcArCHT7SmGDwHI1/9s+Y59fqjTW7IGtdLh3lhltl/yr1GhWw1MnRG2y0PilcmYmtRDQPJvCLHEViZ8C+RJPsTEo89Uz4+7xW4Y9MnmIjFdODx13/W9NZCIfno6qxaGH914/4KCy8hSFkhnrjmhThjVMedGMtLY+46cyw9LocVHCrGkuE76DWdMo/IS4aXpwFXECDXFIvvVdGKpLFkLJrt8yU/+i++CbYpnkwjx8VhhlMg/m+ANhylYNrsvBGqOT6S8Xohskx6/AKYdnOEOWUINfTKBHnyG6KZCoBQTR4qbo94C7M1ouXa1t7jms+GsRktanQEvTM6EckEZNqJXVcHVWwaAb6GNBy7JSBxRLFaFfDJnoenblgQO+o0FCmkItr5Kz7E7mIq8IHqvnUXkw="
