language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "GqFHy4GCPL5SsEfNNPIv71GDw6nJb9b0/DR55x8KAhCQYNH9lWgyulETUZyFyHpDn6HKy08mb+ZInMhmS+V+Tf+n6B0nJ4U5Py2ZkpJQUwUXs4tJy5A0aWMdHrL9fXLCnFrFmtjEjQ2RXIvLi/LSI8AmcbZlAuqsdK5jcGkB2egtFrxQswvKon+UAgk96WJtTMd8xAthfDKoSaypwPtxs5I3y6JxuYWaA3uS1rb8qlMJkIEG51vBcWburGfc7V4O2qGzP15GkWgDQjAG2mm8v4gHFV17Doafqtt8tJNx6fqdhBWEbZST/sLzi5ufaBH/lBdECgR9NywUUKAIXT11B/x6q9XdW/0vTbSytfABExIsAs3SS+zUkyFN6VgPptipPIHVtKKywtO7Hw9pR3SOuKYXFTWPrRaxn4DReGnCXTu0P5L2LLLFRShz6Ki5BS3zcHZKVc7jpdto+ngQUE+r/8l0qO2aVmMmfH9ZF2IuaOqNY3du0IKy8/E1DC8CDT4pB/hg2WhnF0upVNyN6HqS4C9M4aaPpQlq+4iC9d5exWcOA1zMTykdV/2jPmFO521tV7VxaBb6N9mQWYZ2K1QYFKN5SfChl7ViUbRm1Rmjw79/5NoLLWeL48KeZ0oQTUBpvAdm9PI4uhXtRCwztrb9xphwd0MSw+kx/AZCubeyehU="
