language: node_js
sudo: false
node_js:
  - '4.2'
branches:
  except:
    - gh-pages
cache:
  bundler: true
  directories:
    - node_modules
    - /home/travis/.rvm
install:
  - npm i pm2 http-server broken-link-checker -g
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "UYswFXwWNmy2GCKU305xsdZJmYTWGAOuIt78EeBOgZBCEO9jEU7PgufqLtgJpfE/QB2/7eBCNDdcdyMnVbxkWQ6n2itKzo2kaxscstA8lbk6xqKOJ7RGnrHkg/w+8VVIlh2ugl9dYuiqLVHAk8LEkyP1uDDk0BkSMTtG8fprHB4Vy3Ioza1+rvHHX2zavMnoTnE/L4Lhnb9fQGGs32eynIwzUe1kqkbkvwk1js5mlQo3Ha8nzIWbVUZ8QuXDjBv+lAZKmji0MNaQvXzYLGddOYdAr8MqauWGs+B0cLVxaZYMoop355h3koQKUINURUyFXu6jArp3FY225EV7Mph50izJ8c0WxVohqJHgzFufVz3D2/52ffCdTXBDrSQdDlXoAUmcv66QUMdg9PBvh/Yo91W6mbzhCeMZjd/PaZse4sjjSkGwDkyf4OAqB3gpaI4mTui1vKAFHeiuwYMK1YyjNReZxKIyRsTBt/dAqNrDih9z0f+uY1uNIcvik/8S7ZrAe+W4L4Q0dbUW+RzYcqyGf95ZTfNgg5YhRzQIZWM84KD5QbjPhpUMfyTgYFeY96q1gyoubdM7qezq3XHQ4iSgcQuqWDy7hFfX82R0fRT5c2uLDN0MSaYGLIWE8C6uxgZgr91t/u/lhVLX+C+F0QEmpdgmDqHNBfxgkIKfw/310o8="
