language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "FxuWz0OE+LSRiekew1S2bqA8W3JlvZ7kjViRjIbSEFVosSeol/gm75kyKqmceJRaNsfMOqggwsJgbSj2OHg85MvigR6SH5OfNXvBviOqwK0SaeVbSH6Y+MIpOctY9xF/AuhSafYdW2o32Rgnn1yV8xAB5Dm9t0Q/PywyffHWeal2g+urQpffvzpSOhCFBoGrZguiMVjHyc0d5YiyLFaghVUneOwh4opRhBuo0x+dunqjWcjyd0FtBZSGDAYnVcKhGkIwt/48uT3MXDUbrw43+9mjRpfgxZ6JSNIk15X8kjjhdntIB2pq19D7jS4dKWPdJUiPOpDP4Y2gWKv5ejH0xtDXctly4oO7rKQIHEemZXpxXWXclaXQ9aNzg395972U+Zv2zeFnef7aJTucxVu46ZIWzs4f9e1oPVoZtDp/eootrbBJUM05WNfqhYuzIaWmk7A8ptx4ynOTLiwks9/5V8C9R4aoeJuTzB2mCeVqwP0TJF2sGUKIzo2wdGHQw4uo4l/SDvbehszRCfIg6pMqfzQ5gknxI2jeH3g2s5DcICc906IABzuz4pJCX55lBTEz+p1ZI5dlYgl3YEbsamMeCUPEBHfu/+o39J/QB0XsN9Qp65Ay1t6io1R4lrRIQN6qYQixZZ9V6UAPUprfCVt/JWzwp41N6aIa3XgSbivP3NY="
