language: node_js
cache: bundler
sudo: false
install:
  - rvm install 2.2.1
  - bundle install
env:
  global:
    secure: >
      "ucL0lDQryc04He8qLIsvsYVAMpmj299PhuXBcsRP7MuIsYj3txpmG66aGP6sjZbewh8p8/6lYv5IU5PtG4f950B5qpkWMYrZbQhSdnDS+1wtGNfa88t+a27ZAmvRb8iWkJdNzevUG+OES053uFr9oxd0/zm3+1uBm0PYZBTHrCckpjT4y937lix0QvSRP/mO7s40wQecYuOh8awdkpsMBZ6Zu54YT3CUD07wLPKdGvWD+7kUFFSFgGRR09hhpIWmaAtEJ7+qf2fuYpvapXH5i+NRAAIVGwk7OR6lqV4HmMAQkio1OtZP9r/JQJYmhOSKLgi+zvZFfE7+Yjm+Er0d9DovpPl1xTJWTXDnLvMtccIhVVSsStQYe64PsGHLHAEng30uUBYW+x1z4XI3G5P1OAWNCRrkVtgIhyK3vxNRbTVgy05v7rz8hH+cxvZfa/rtKf48EYiMnOYkB/hSaOeYQ16umYCpErXKJFf1yHBebCXgz9DLK4f0x+vshi/q0CUlz17U3MWCEVbjB1K3C5LswEboUIiimQ7ilgUSvVEmynlHeroczg+0n3r5RMDC6xTKdcTIUdLqhIWsvRfGU1RbyKqW9LtO6939S9ZqGcf8ktDbKgfkXFKrObanTQjyIIGjP2jAeJs35Xt/nNzTleij7LUbNEide7ghDcLbw51NHDI="
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: contentascode
  CONFIG_REPO: docsmith
