language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "Qkw6UtUx4VaPP8FyNT5MywkhK+lb5xvOeiPVkuRdw/bIPjPIcoXjZ6yVL8xksPcQPEnusNqVQ/3iYtim47QLRqYP+Ae50XXBRHx+czhWetVY2NMicu4Nx/K86SEz8XPG34uDC+a2SpmENMR+Ys67R7dDn7EYheCoWVM8akqPtQFWL+HbuFYpx0Q3EqCdHS7SULTidChi0fZXrb1gDNYlJ1EsK0oSxH0wTQ1l4aGiVVFDqlV1slyjGmMIoHh0ntJGzsHC0CICB0rWEeH1dVkeic6K61McKIYyny+C7nRxuiLm+4IvM9W0EIc/+DsYPkKfZsHvD2A5LpZF9IbraEHdtUnHuW7IQeHxJayhyNuklyBessswmvzmEVvB8Ud/d84iYAXEr93ksyEFkCTjXyxFV4OMLgdJaO1/Gv4eroVtkQ/VPwct4QF+S0su7P1eJJOAqRJVlfaRZ7jtEgbfH0DjVOccs920UnX6VdDqksskuMm8yrq/QuBhPNBx5Px/BUmhLror+TMfJY9dLWYeMhjxlXqbwse1mp6OZSgYyVnlaHTWjIPRtbJE/uHzrQUJabj3q9XkUbajbRqWB092hXM5BabGugs4TyLqF7PUfFaivTNKdojDfEiuWfFwXak30WzADbAzPxFDvIB36W7jwqJfFSYGREzNZaP1t92K4M/RYiY="
