language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith
    - secure: >
        "kBstAaz5cE0fgrq6L5XlAIgvXpFyNioHJJe/7U3uPzaed6wC+aReD4qbz5YVWe/BF6rc7AKiUjoLv4YYmxbV768NZkfPIFGRuDJdmqGtqKHj5AQ+7Qr4jY5d1G5i1l5CIvuCuQAItmQsI0ZtKIYahxba8e6McFQZ5P9LTojXHnQVqtAaRcTF6CqmlZ/s6h0kas956Nynk4SPbZKDiqAuZCPBri4Cdbb3l9bAMkIH2aHkGm+9AX3+BIZUdTg+to/EW6BEm89JvtIf4PkAO1Fi+xYmWGPjbQwTyTcTfQGEevkavo1XQ4fOOclooXojaDS+9GxOkabJ+kkSFYz/HCT7EMyxLV7eI9MVAypD1lMH20WxuQKF22AjmIpNxbk94vV5K65WPXntW1NYhWOLLTcoYF/26J/8cp4TulmxhvYt+DqkF9Tz0iJXoGxkqo+VwFsBcPp2A1LyC+DsTVPX3RBjCmU57DQX8W3B92fyr9sU05iRGQ08VdjKAEUgLJvDi3n8MXMKi56OqiWQY9vN6EWV/OH1xU9gVExIxkFRKTGz1EezPDvJ/qN3yxLiYMW8BrlHJEviJENx/EJ/Qmd22M4+OADh5I0L6wZsESn+0MXi88Ykg9ILByt4uIOv6DtqtGqv/7Ia/BI+sq352Q1G9nybuno0bTlqeZu29P3Tkoh4h0M="
