language: node_js
cache: bundler
sudo: false
install:
  - rvm install $(echo .ruby-version)
  - bundle install
env:
  global:
    secure: >
      "nD5L/R/tc2Az4JC5XGHTWwEHB5wRArJAHIUDKJ6L3Ha0d4e6eyNRjQKoDyQjwk30CZin3fWhOhDkrilKbwcWVGMDNaTFliXURtPBdyIHrxrsAegcHZyheMIgpqGQYSaLzF69/OiT3gauvF1ZTcpLzfWoFAUPYDjlqa3xxAxmktY9dBqhYki0vhJMgD/8SL204CcNvUhiM5+85YNbT7U0Yg4nvXS3XAoHqaqK3bNAEWBsbSQHxxNFCuDrvWb1+iQKGKJ8ZyIz174+Pa/0kwLCdm8nzEMoC0GFIVzAMvrVoA8eLKVPa9ker+QBuXLlUWHy3pg3P6DIuyvGEBgOqiNIEHLJz4BpSUXLWeCsJcDmumlzyIpbrL15BhtQqJAp9rQTvULizd9ii3UFLZ4P87mqQAKqZ4l+/RfcEM4TKgnRbpkqE3Q3nuKNMNGNnC+g+NNK7rfLuIM5LBcudBLsKWLiuJVkGRxs9WFpZh7guJbI48kNXfWqDmsu7Ztv8+1CbbB7LjApTJAa3+KduisL9W3W6SO2sJMFmZKHjrvyYQ3CP1vzC5rf7kdHXh5ryM0bnx48PrVyL33ZfnYbMNr9mXBz+DPrSrbzrHH+XIhryvHh1a74KQFvv1kcg28bS6Ou3g01yK9gt7Xv0ftPKCf4O37cCfF6xt/jMv4QEQDrIzpoQcc="
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: contentascode
  CONFIG_REPO: docsmith
