language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith
    - >
      secure:
      "VTEY+5vvzS+LsPe23R4eTNDffsmuqtb7MIclDPJttfD8Fb5XhYAhHcW9kdcCa7o/UfR0joEVggmwC7keaqixqswO4j69rO40RuQ00JGWCs+Aviu76JOVNI8wdTktTyxXA/6IeuS6CGn+EWOGpN5rzDHYql2BuRAgZM0RMw4huTBaA85m1mMudP/qtAhda2U3w8ZbHX5+ll9aIFbfVLDFE8pPOSy1LtCL/n5rYNXeWysl4XyuJzo/MQN6DPaF5EzyNz4n1UFCkYcrhDsmVHd+6JDi5iIwYj4WunE/ULzEsJ/D/x+wZm2F70zw91Ux73pNZGhFp/yCBWk4uEMyiEFva3el9Nw636v3YZz5VzfmUVm8zaou/XWfxKAutPHuP6qYGHCFzIlyNU2Ki1mnJ5qMN9PnSRFqW18gzh/g/HrvGztsD7AEJyeiVxj1P3/qBt83UJnHRi13nENrlCwTLxGesz+sOckIJ/VgEGOHVJ3uQnhMKj8FXDs6GjbRNadp3pj6DPdz0qeudF7ALpEZV1Tx7LN7P8F3PTOMmBd/QAeUts8JdvFFf7jsyqZLvMLNU84qOHd0dHT/np635dp28CPFHtJm2omFQcEUffSXpVrArcJPyO/4Wqm2G2bDE2f5Qkju4/TpRFwbTRBkjasoa15Pl2OoxPJa4buK32ltACKuMnc="
