language: node_js
cache: bundler
sudo: false
install:
  - rvm use .
  - bundle install
env:
  global:
    secure: >
      "U6jZV2Ocesa4Fjf1W8yYi1LiqoYUQ16jXHLgMVo3fryat01o84s6OZV0W4yWLDpO+XoHDrotywiepCK2Ri3wQ3X0telrJ8tj26qjSlNATDEgC+TbW5XL6RYLGvxMbcvk8gZjFJ/8aWCrNs6eU3z9dlshIdagvDP7IZ5IGZEZQQiG9QtBBmhpG3NFOaP6IwqzKAX6M13kv5haXWcetlR89CpoicaYeCrKopDp/jdeCs/BfcgUBn3Ouc9lZoj/de2c/XFY0aWaICdnayUcg5cc3bXl4YdUkkFXc+jM0AqLFxaf02+rZJrclTKkTlhdnGTqtssc1U4lYEMPAC4mkBUKTN/OMTCznUpE1e3qG/fg5KvrguwNpGD6Gc7pVXnWoxYB7eHOsQiBLj2SsFeYXdACMfHGXgUVR9F5choewMbZHedm9U6gHKIvUW8DUH8NZ0S+xjy2hjSsezAV5tvQS64A5v9kfD7vc7sVF230yW5OWDh7UcZ8eJUPhwUWlFiR53BQFfsMTruq37rfCIgWZOSriunOpmRbtHmLJuKU7tJW/HW2iD04mWJ9SjeJsUE8UCupY9QCB1ksiLBcwaUZHd6zxZaL3fVo9n9Bj6OvNLHewZTOZEoS1khi0ngI1xS1AF5yZbX/W2APZ4qbYACNs4xV8N8+K8rUUt8lZOgT3xKlSoI="
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: contentascode
  CONFIG_REPO: docsmith
