language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    secure: >
      "qIXvii7aydzHOO+8eOgxeu3G8gzFqH/Xv6kp8FX0yOHISEfshQTE4ppvH5rw4CDYFBpscOb46Rxz4fxkngn/ZyFap1pzzMfN3mo7iGWFUoev+juCCup91Vz/LXV7sDUou5QeAo+v186Byu44XPBPdlkN1+4X0bpndodSN8kSUnzrhzIkpzHFlJK0sNXINYi2JoPYAEL37PwWJracWNz1Xeq56LCp9Xon9HmAJsff9oqyWPHGQk4dlqijqIFuI6J+ZP0uCCq51zkrh40qYcS4aCQvCId8vjSERUkmFYEizfPJ+YJkZaOyefP++ohLg76q9YjO0vgoX1GLuyr397r5zAZFEhY6xm+SxOPlm6Eq1t8iToSMEyq6ZJyE1KaJ2673UuytYxwfTaDVnYEdPx6PAe4WOFaxL4WkfiNJqrU8ktn//67iPyPWmOUbBWapWh9/LhLy3pxB2WbejbXQF2UVWhk0yZqD2USbY41/97J1BCIy61alOnBFS9NHyDZov15zTlYmS1wTr9n9I33wucX7+7ySYj0o5tjqWsdL/iNYnt7LANRGPXgUwHlm6enpNm1rCPnp9TtAPudBEAFfsEnBBtK6twwPZC6orffQlUbR4VyEW+G9B+S4HgSC0zVTePK4AtFJXfeMOapkwpRAUjG64A4/+xUTP53mR5mkZlK3kdM="
  GH_USERNAME: jmatsushita
  CONFIG_OWNER: contentascode
  CONFIG_REPO: docsmith
