language: node_js
cache: bundler
sudo: true
install:
  - bundle install
env:
  global:
    secure: >
      "kMErFVUrFKfv5vk4/Qc5TOwwUtQzldmi2ej31g7ofCf05mg8mrKyEdJWJztaqEU57Jput5r4EBjviZbcb+HMMY0gYVD2KCyOTVVR5ioK84V3oD8nVf4QkFgzOXw5iyhnJ3Q8IapHneqS1GFHzRNzEufsDGd0NL1U9JtEpDuqhnLP1RjqwPiaddDvEhX16/v9brl77a+Y096EJMPxxA/+H2TO+mHIwOgCSTjmnMfUBHp/kTxsRMskUzRd/p50ZrvMm5e7z4J81IM1fctrjHCYUBCUk3MzX5wJ7QbpaVgPsdp8uAwAtkCT2OryR5WEJGLXc0m64Wk5iG4Ibwnq+TNGes+I5NxsQ+vLua5tEt7CihKviBXQUPpJld01rfGFrz1JTe7f56buXL6t/xL5nSpSnH7m3WlR9ms+aYQ6mRJm3fuQvLIYJ/wDa9OiMl7OTLvNCvIWQZwatVVZAB47pl+DuBPCUUTQSf10vlsLpzmEQJdi5njubJ7MckEsAJW+5hqC+/lAMqM7qqxEMlP1eHsx+X4b5tNW9v5LEm/W19FLkWX8AHud19jE5F5CFr5ZZcTsSHQ7OuJFNMMcieEL0ea3Ax6TVuASxO+nhUWphq2AuZKH+Pa5dJmhrcr61guPimA1gPRwKtn7F5He4PZcpaDnQ+xw5uPagOHMpq/9RzEvtKo="
  USERNAME: jmatsushita
  OWNER: contentascode
  REPO: docsmith
