language: node_js
cache: bundler
sudo: false
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
after_script:
  - 'test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy'
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "qScT6z/MeYb9Xx1sgptUpZEum3QJGCfOz4eIA/xEAVF1/aixvg2nwJT5isk2rRLD+PhBOXc6yd3wmAMoPYomTvt+gIfAMb723+z76zAUqNvZ4GZxl+EA6vuEyWQkcc+5KNAzUw8vN1k9Kk/X8ED6V+1ESq8n0l9nDiR6iP82J8rdo0ZcPwiIbUETi4nJMaok3+qJu3LNe8PHOIpJzSs9d9Hu2ldxHDSjp18qZggb/6ZRMZrGow0M14E51+gIC0bROhE8zKSiocp8OWe0PC39MugvNpO8YpknujgaXPaaqIzqq2k9PWDsqRkISCiCPbTatTN4cNkgnk5S849/W4TXwY9INyhBA7WIB2JzvuGUXH7WalrnVDLfNWLrjOIkrCM/nr+8BJvIVeC1uuXvmHADPORmD/T6qNDK0O4/3kZobsxplKEaT/qf/dUimfWqe9aWw9Frw94iKKCPc6lzWpB7t0GEptfHpxHQlFb0pqBu+20MM2GeSX472cTxV/xUpgZ37rT3zCjP01JRfKuM3Aqgli0tmIWQwtVpLs3Ig9hImLYXIP4LLNMtKAEt6KcZzJnTSwMtTk/NRgEZaB/LlCSoYbZ9Er0AlkHef4KE9zEvvbd77dXr92EJfhO7MsB74PFqJerIMW5G8HPt2ispwD5fsCyKRyvkjqJpezMzaxlEAH0="
