language: node_js
cache: bundler
sudo: false
branches:
  except:
    - gh-pages
install:
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=contentascode
    - CONFIG_REPO=docsmith-init
    - secure: >
        "GbO08s4bUvfvEQz9VXX74uP3+R7/ddlGCgxpWxOdoRv5aJx16GW3g9LvwqtjZ/bgwEQMWdvRR6iG10MIBEFq1xWht8sArgQfF7E7/hnLqxw/8WntXgOg2zXdW+BIxEsmJliarfg2nvw81cD/c4bWJ4vXnnSDFbdyLm7+bMsD/jFVxBjkctAyNNszs5GDP4XZltMFVuRurjAPAES7xUCjW2hPWXq5yBmye9YtLYtzYrL5GV+AFt2Br1LrFGmyCIqUSh8tmiTTMx6oiylogQQEMqyfW5Mjm32uZY834IKNrnNyXcdRIKm0ZADUX83+I56yJz+KeamhR9w9v3/gOE7kjrQcj1M+cdwetwFJaE4u2sLOAFmDAAcay4BZmBJmafyUN862jTtSy8q58LKL6N7VzH9ghKu7ZP3mU/WqQeHk9mga1xat4xZbwtjyTA7AOYbpmlVZn3CDcoFfPdhP6+rqffuFV3uSsJ4WmlfsM2ceamFObHbh7fcxdytJDwFFo4c99cytO43DBrLVC1NIURsp5IA8QigMuHFyVDhAx3LWEsVMQ9nlaV5F6Ga5ZHYJvUtKrjOhM/92iPBi1ENT4R8ylvv/Q0Agf+zgBRWP/rOvNgHOz1d5d0ipo+bQaA2uru3kAjhPQFKiaLfZdhORs5JAVFLVuZa5FuTsF29DIHUDzGQ="
