# Dependencies

markdown:         kramdown
# markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Content as Code
tagline:          'Developing workflows and technology to improve content re-use and maintainability.'
description:      'Developing workflows and technology to improve content re-use and maintainability.'
url:              http://USER.github.io
baseurl:          /REPO

author:
  name:           'Your Name'
  url:            https://twitter.com/yourtwitter

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "lax_spacing", "smart"]

github:
  repo:           https://github.com/USER/REPO


gems:
  - jekyll-sitemap
  - jekyll-gist

# jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/OWNER/REPO.git
# username is user linked to the personal access token for pushing to the github-pages branch
# ownner is the user or organisation for the project. 
# repo is the name of the repo for the project.
# Branch defaults to "source" for OWNER.github.io
# or "master" otherwise

username: USER
owner: ORG
repo: REPO

# branch: source

# Settings for deploy rake task
# This destination folder is probably not necessary and we should either migrate out of jekyll-travis
# (which might be a good idea to avoid rake+metalsmith+...) or submit a pull request to default this to 
# a temp folder of some sort.

safe: false
lsi: false
# pygments: true

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml